version: '3.1'

services:

  db:
    container_name: db
    image: mysql
    command:
       --default-authentication-plugin=mysql_native_password
       --sql_mode=""
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9000:80
    environment:
      - PMA_ARBITRARY=1


  welm_flask_server:
    container_name: welm_flask_server
    build: ./python
    restart: always
    depends_on:
      - db

    ports:
      - 80:80



volumes:
  db: